-- MySQL Script generated by MySQL Workbench
-- 05/03/15 19:09:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema widgets
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `widgets` ;

-- -----------------------------------------------------
-- Schema widgets
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `widgets` COLLATE utf8mb4_bin ;
USE `widgets` ;

-- -----------------------------------------------------
-- Table `widgets`.`changelog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `widgets`.`changelog` ;

CREATE TABLE IF NOT EXISTS `widgets`.`changelog` (
  `change_number` BIGINT(20) NOT NULL,
  `delta_set` VARCHAR(10) NOT NULL,
  `start_dt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `complete_dt` TIMESTAMP NULL DEFAULT NULL,
  `applied_by` VARCHAR(100) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`change_number`, `delta_set`))
ENGINE = InnoDB
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `widgets`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `widgets`.`companies` ;

CREATE TABLE IF NOT EXISTS `widgets`.`companies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `website` VARCHAR(155) NULL DEFAULT NULL,
  `address` VARCHAR(155) NULL DEFAULT NULL,
  `city` VARCHAR(155) NULL DEFAULT NULL,
  `state` VARCHAR(155) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `widgets`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `widgets`.`employees` ;

CREATE TABLE IF NOT EXISTS `widgets`.`employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `company_id` INT NULL DEFAULT NULL,
  `is_admin` BINARY NULL DEFAULT 0,
  `is_locked` BINARY NULL DEFAULT 0,
  `attempts` INT NULL DEFAULT 0,
  `password` VARCHAR(255) NOT NULL,
  `plainpassword` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_users_companies`
    FOREIGN KEY (`company_id`)
    REFERENCES `widgets`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COLLATE = utf8mb4_bin;

CREATE INDEX `fk_users_company_idx` ON `widgets`.`employees` (`company_id` ASC);

CREATE UNIQUE INDEX `username_UNIQUE` ON `widgets`.`employees` (`username` ASC);

CREATE UNIQUE INDEX `email_UNIQUE` ON `widgets`.`employees` (`email` ASC);

CREATE UNIQUE INDEX `phone_UNIQUE` ON `widgets`.`employees` (`phone` ASC);


-- -----------------------------------------------------
-- Table `widgets`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `widgets`.`groups` ;

CREATE TABLE IF NOT EXISTS `widgets`.`groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `widgets`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `widgets`.`customers` ;

CREATE TABLE IF NOT EXISTS `widgets`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `plainpassword` VARCHAR(255) NOT NULL,
  `email` VARCHAR(155) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `instructions` TEXT NULL DEFAULT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `verified` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COLLATE = utf8mb4_bin;

CREATE UNIQUE INDEX `customer_username_UNIQUE` ON `widgets`.`customers` (`username` ASC);

CREATE UNIQUE INDEX `customer_email_UNIQUE` ON `widgets`.`customers` (`email` ASC);


-- -----------------------------------------------------
-- Table `widgets`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `widgets`.`orders` ;

CREATE TABLE IF NOT EXISTS `widgets`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fulfilled` INT NULL DEFAULT 0,
  `unfulfilled` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `widgets`.`companyToGroups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `widgets`.`companyToGroups` ;

CREATE TABLE IF NOT EXISTS `widgets`.`companyToGroups` (
  `idcompanyToGroups` INT NOT NULL,
  `companyID` INT NULL,
  `groupID` INT NULL,
  `groups_id` INT NOT NULL,
  `companies_id` INT NOT NULL,
  PRIMARY KEY (`idcompanyToGroups`),
  CONSTRAINT `fk_companyToGroups_groups1`
    FOREIGN KEY (`groups_id`)
    REFERENCES `widgets`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_companyToGroups_companies1`
    FOREIGN KEY (`companies_id`)
    REFERENCES `widgets`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_companyToGroups_groups1_idx` ON `widgets`.`companyToGroups` (`groups_id` ASC);

CREATE INDEX `fk_companyToGroups_companies1_idx` ON `widgets`.`companyToGroups` (`companies_id` ASC);


-- -----------------------------------------------------
-- Table `widgets`.`customersToOrders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `widgets`.`customersToOrders` ;

CREATE TABLE IF NOT EXISTS `widgets`.`customersToOrders` (
  `idcustomersToOrders` INT NOT NULL,
  `orders_id` INT NOT NULL,
  `customers_id` INT NOT NULL,
  PRIMARY KEY (`idcustomersToOrders`),
  CONSTRAINT `fk_customersToOrders_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `widgets`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customersToOrders_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `widgets`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_customersToOrders_orders1_idx` ON `widgets`.`customersToOrders` (`orders_id` ASC);

CREATE INDEX `fk_customersToOrders_customers1_idx` ON `widgets`.`customersToOrders` (`customers_id` ASC);


-- -----------------------------------------------------
-- Table `widgets`.`groupsToOrders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `widgets`.`groupsToOrders` ;

CREATE TABLE IF NOT EXISTS `widgets`.`groupsToOrders` (
  `idgroupsToOrders` INT NOT NULL,
  `groups_id` INT NOT NULL,
  `orders_id` INT NOT NULL,
  PRIMARY KEY (`idgroupsToOrders`),
  CONSTRAINT `fk_groupsToOrders_groups1`
    FOREIGN KEY (`groups_id`)
    REFERENCES `widgets`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_groupsToOrders_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `widgets`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_groupsToOrders_groups1_idx` ON `widgets`.`groupsToOrders` (`groups_id` ASC);

CREATE INDEX `fk_groupsToOrders_orders1_idx` ON `widgets`.`groupsToOrders` (`orders_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
