CREATE TABLE IF NOT EXISTS `companies` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `website` VARCHAR(155) NULL DEFAULT NULL,
  `city` VARCHAR(155) NULL DEFAULT NULL,
  `state` VARCHAR(155) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `countrycode` VARCHAR(3) NULL DEFAULT 'USA',
  `zip` VARCHAR(12) NOT NULL,
  `address` VARCHAR(155) NULL DEFAULT NULL,
);

CREATE INDEX IF NOT EXISTS `companies_zip` ON companies(`zip` ASC);
CREATE INDEX IF NOT EXISTS `companies_countrycode` ON companies(`countrycode` ASC);

--//@UNDO
DROP TABLE IF EXISTS `companies`;
--//
