CREATE TABLE IF NOT EXISTS `groups` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(255) NOT NULL
);

--//@UNDO
PRAGMA foreign_keys=OFF;
DROP TABLE IF EXISTS `groups`;
PRAGMA foreign_keys=ON;
--//